name: folder_cli
description: >-
  Folder_Cli allows the creation of folder structures using a modular appraoch. It can be used like this `folder_cli -c 'create' -a 'module_name'`.
version: 1.0.2
repository: https://github.com/DeTuksa/Folder-Structure-CLI

environment:
  sdk: ^3.0.3

executables:
  folder_cli:

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
